### ISSUE TITLE
Unsupported Image Type Error

### ISSUE THREAD

**Issue by gweigod** [HashLips/hashlips_art_engine#350]
It was previously working for me, I added some new layers and I'm stumped with this error.
It's not an issue with any of the file types, all extensions are .png. I did some trial and error
removing layer directories to figure out which folder of images is catching the error.

The weird thing is it generates around 0-20 before likely erroring, it will successfully generate all specific images under
the folder it's erroring on. So I really can't pick out which image it exactly errors on, because it will successfully generate each image and also error on each image.

Really weird bug I've encountered.

(node:32160) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (C:\Users\Admin\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Admin\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Admin\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Admin\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\Admin\Desktop\hashlips_art_engine-main\src\main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Admin\Desktop\hashlips_art_engine-main\src\main.js:180:10)
    at C:\Users\Admin\Desktop\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:32160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jremrant** [comment]
Have you found a solution to this?  i am experiencing this very issue

**Comment by gweigod** [comment]
> Have you found a solution to this? i am experiencing this very issue

I did somewhat find a fix, after hours of trial and error I managed to just redo the layer I was working with. The only thing I did different was not add a gradient to the image. I'm not sure if it could be gradient causing the issue or not, it's the only thing different from what I've observed.

I'm not sure if the images you are working with has gradient but, try and edit them slightly, give it a fresh name & folder.

**Comment by TeeLeafz** [comment]
I had this same issue and did some digging - tried looking for the problem files thinking it was a transparency issue or color space or something and found that I had named them with a "-" (like Green-Eye#5) once I removed it it was fine and continued to work without having to remake any layers.

**Comment by gweigod** [comment]
That's odd, myself it was never the name but the image causing the error. I guess either way it can only be fixed with trial & error.

**Comment by jremrant** [comment]
Trial & error didn’t help me as isolating layers didn’t solve the errors … I ended up downloading an older version of hashlips, slightly reduced the size of the image & it hasn’t had a problem since?!?  My art was 2048x2048 originals & output files were changed to 2000x2000 … it works now.
Thankyou for assistance

**Comment by gweigod** [comment]
> Trial & error didn’t help me as isolating layers didn’t solve the errors … I ended up downloading an older version of hashlips, slightly reduced the size of the image & it hasn’t had a problem since?!? My art was 2048x2048 originals & output files were changed to 2000x2000 … it works now. Thankyou for assistance

Uh what you did is trial & error? I noted that it seems we all have different things causing the error. I did the same thing you did & it didn't work, you might of done the same thing I've done and didn't work. When you try many different situations unknowingly if it's going to work or not, that is called trial & error.
