### ISSUE TITLE
Support for Solana Metadata

### ISSUE THREAD

**Issue by SethCalkins** [HashLips/hashlips_art_engine#49]
How would I go about adding an array to the outputted JSON? I'm having an issue with it being an array.

```json
"creators": [
  {
    "address": "SOLFLR15asd9d21325bsadythp547912501b",
    "share": 50
  },
  {
  "address": "SOLFLR15akjwjwk3k3k4jlk3kljdlklkw2lkj2b",
  "sharee": 50
  }
]
```
As well as 
```json
  "collection": {
     "name": "Solflare X NFT",
     "family": "Solflare" 
  },
```

This is required per [NFT Metadata Standard](https://docs.metaplex.com/nft-standard)

**Comment by CryptOhGee** [comment]
I'm having the same issue. I will let you know when I figure something out.

**Comment by LiamKenyon** [comment]
`  "seller_fee_basis_points": 250, // this defines your royalties (250 = 2.5% || 1000 = 10% || etc)
  "collection": {
    "name": "Item", // the name of your collection
    "family": "Item" //the family of your collection
  },
  "properties": {
    "files": [
      {
        "uri": "image.png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "address": "CXXXX", // the address you want to receive your payments
        "share": 100
      }
    ]
  }`

Just add the above into extrametadata

**Comment by SethCalkins** [comment]
Thank you, this has been resolved.

**Comment by MorrisBX** [comment]
This doesn't seem to resolve the issue, the metadata structure is still not fit for Solana...well at least not for the metaplex candy machine...
